export MAX_BUFFER_SIZE=50000000
export SUPERLU_NUM_GPU_STREAMS=1
export SUPERLU_BIND_MPI_GPU=1
export SUPERLU_ACC_OFFLOAD=1
export GPU3DVERSION=1
export SUPERLU_NUM_LOOKAHEADS=1
#export CUDA_VISIBLE_DEVICES=3
export MPI_PROCESS_PER_GPU=1
